### ISSUE TITLE
Purpose of auth-api client

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel-go#161]
Currently I can only use the auth-api client to manipulate or read the service user. I am not able to call the api on behalf of a user, I'm not sure if this makes sense. In my opinion it would make sense to change the auth client to do api calls on behalf of a user

**Comment by livio-a** [comment]
> as we have refactored the zitadel-go lib, is this still relevant? @livio-a @adlerhurst

IMO we can close. @adlerhurst please reopen if you see it differently
