### ISSUE TITLE
received unexpected content-type \"application/json\"

### ISSUE THREAD

**Issue by uppercaveman** [zitadel/zitadel-go#282]
run example/auth

call failed:  rpc error: code = Unimplemented desc = unexpected HTTP status code received from server: 404 (Not Found); transport: received unexpected content-type "application/json"

the client-go branch next not fully developed?

**Comment by hifabienne** [comment]
@livio-a can you help here?

**Comment by uppercaveman** [comment]
using postman tests is OK，but run example error

**Comment by AshishMittal02** [comment]
i am also running in similar kind of error
`rpc error: code = Unknown desc = unexpected HTTP status code received from server: 464 (); malformed header: missing HTTP content-type`

**Comment by livio-a** [comment]
Sorry missed the notification... do you still have the issue?

I tested using the `next` branch and could not reproduce
Are you using zitadel.cloud or a self-hosted deployment?

**Comment by schlapzz** [comment]
@livio-a any updates on this one?

**Comment by fforootd** [comment]
Hm usually that error means that there is a network problem with the http2 connection not properly reaching zitadel.

Can you share your network setup (i.e. proxy config)?

**Comment by schlapzz** [comment]
@fforootd Xes you are right. The issue was the AWS ELB. After we switched to an AWS ALB with HTTP2/GRPC support, the error was gone.

**Comment by fforootd** [comment]
> @fforootd Xes you are right. The issue was the AWS ELB. After we switched to an AWS ALB with HTTP2/GRPC support, the error was gone.

Perfect, nice to know!
