### ISSUE TITLE
[v3.0.0-next.2] Post Logout Redirect URI proto set incorrectly when behind TLS-terminating reverse proxy

### ISSUE THREAD

**Issue by heikkilamarko** [zitadel/zitadel-go#285]
I've encountered an issue with the post logout redirect URI protocol being set incorrectly when my API is behind a TLS-terminating reverse proxy. Despite configuring the post logout redirect URL with the "https://" protocol, the SDK implementation sets the protocol to "http." This is likely due to the reverse proxy terminating TLS and calling the service without TLS.

https://github.com/zitadel/zitadel-go/blob/aad6fea5e41f95579aa0e7c033b0952500ce3d4a/pkg/authentication/authenticate.go#L131-L133

![Screenshot 2024-01-08 at 10 43 37](https://github.com/zitadel/zitadel-go/assets/3757314/0985becb-b5c1-4eb0-b0be-c7a585a1cf8f)

**Comment by hifabienne** [comment]
@livio-a can you help here?
