### ISSUE TITLE
AWS Lambda-friendly alternative to `key.json`

### ISSUE THREAD

**Issue by brianfeister** [zitadel/zitadel-go#370]
So, jamming `key.json` into my Lambda function is an obviously bad idea. S3 is maybe a bit better, but I'd really rather not have this living in a bucket somewhere, even if the permissions are quite locked down. Even then, having this critical file only come in via HTTP transaction introduces a latency that I'm really not happy with.

The only mechanism that seems to carry some guarantee of relatively fast bootstrapping of a Lambda on a cold store might be AWS Secrets Manager. Is this the preferred approach?

Am I missing something obvious here in terms of what Zitadel's "sensible default" security posture is on storing `key.json` in a Lambda Serverless (Golang in my case) context?

**Comment by brianfeister** [comment]
I've found this (very undocumented old bug report + fix PR) that seems to implement a workaround via `middleware.JWTProfileFromFileData()`

#82
#83 

But when I implement it, I get the following error:

`Failed to initialize Zitadel CLIENT2 authentication: Get "/.well-known/openid-configuration": unsupported protocol scheme ""`

Is there an example of a proper implementation of this?

```
var (
	issuer = flag.String("issuer", "<my-instance>", "issuer of your ZITADEL instance (in the form: https://<instance>.zitadel.cloud or https://<yourdomain>)")
	api    = flag.String("api", "<my-instance>.zitadel.cloud:443", "gRPC endpoint of your ZITADEL instance (in the form: <instance>.zitadel.cloud:443 or <yourdomain>:443)")
	profileKey   = flag.String("profileKey", "<key.json file as string>", "profile key")
)

func main () {
    ctx := context.Background()
    client, err := auth.NewClient(
	    ctx,
	    *issuer,
	    *api,
	    []string{oidc.ScopeOpenID, zitadel2.ScopeZitadelAPI()},
	    zitadel2.WithJWTProfileTokenSource(middleware.JWTProfileFromFileData(ctx, []byte(*profileKey))),
    )
    if err != nil {
	    log.Printf("Failed to initialize Zitadel Client: %v", err)
	    return
    }
    log.Printf("client2: %v", client)
}
```

**Comment by brianfeister** [comment]
Also, for a bit more context, I found this simple method for binding a given JSON file to a Go ZIP bundle, but I'm using https://v2.sst.dev/ which obfuscates some of the Go build / bundling, making this less straightforward.

https://github.com/aws/aws-lambda-go/issues/206#issuecomment-507718183

**Comment by mffap** [comment]
@brianfeister, I believe you are asking different questions on this issue. How can we help best? Should we provide more information regarding best practices on AWS or help you with an example implementation of `middleware.JWTProfileFromFileData()`?
