### ISSUE TITLE
missing non-deprecated endpoint to obtain U2F IDs

### ISSUE THREAD

**Issue by demircis** [zitadel/zitadel-go#392]
The ListHumanAuthFactors endpoint in the management service did return the ID of the auth factor. This endpoint has been deprecated in v3 in favor of the ListAuthenticationMethodTypes endpoint, however that endpoint does not return the ID but only the authentication method type. If we want to programmatically remove an U2F token, we would need the U2F ID (RemoveU2F endpoint).

There is a ListPasskeys endpoint but that one only lists the objects of the authentication method type passkey, so no U2F tokens are returned.

**Comment by hifabienne** [comment]
Hi @demircis 
The endpoint for listing all possible authentication methods of a user, is meant to be able to build a login ui, so you know which ui components you have to show.
From a first glance i have the impression that we missed to implement the listfactors endpoint.
I will move the issue to investigating, so the engineers can have a look at it

**Comment by stebenz** [comment]
@demircis As I see that there is already an issue created in https://github.com/zitadel/zitadel/issues/8833 I will close this issue, we will keep you updated there.

Thank you for bringing it to our attention.
