### ISSUE TITLE
zitadel-go sdk issue

### ISSUE THREAD

**Issue by prajwalpamin** [zitadel/zitadel-go#408]
Im calling ListUsers function from zitadel-go management package, and im running zitadel service as well. Im getting rpc error in 404 in my service and in zitadel im getting unable to get metadata from context. 
im not getting which api is being hit from zitadel service please help

**Comment by hifabienne** [comment]
@livio-a can you help here?

**Comment by muhlemmer** [comment]
@prajwalpamin can you please edit and supplement this issue.

- Provide a clear title of the problem. The current title is too generic.
- Please supply a minimal and reproducible example. For example a simple Go program with some hard-coded options that makes the failing call to zitadel.
- If you are self-hosting zitadel, please share your setup.
- Does the call also fail against zitadel cloud?

**Comment by prajwalpamin** [comment]
No it doesnt fail in zitadel cloud but in self hosted environment its failing @muhlemmer

**Comment by muhlemmer** [comment]
Please share details as requested.
